//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace cafeteriaPiedad.WS_Conexion {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service_BddSoap", Namespace="192.168.100.84")]
    public partial class Service_Bdd : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback numeroPedidoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaProductoOperationCompleted;
        
        private System.Threading.SendOrPostCallback BusquedaDocumentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegistroPedidoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultaCategoriaOperationCompleted;
        
        private System.Threading.SendOrPostCallback TotalPedidoOperationCompleted;
        
        private System.Threading.SendOrPostCallback EstadoPedidoOperationCompleted;
        
        private System.Threading.SendOrPostCallback BusquedaClienteMovilOperationCompleted;
        
        private System.Threading.SendOrPostCallback TiempoEsperaOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarProductoOperationCompleted;
        
        private System.Threading.SendOrPostCallback guardarActualizarClienteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service_Bdd() {
            this.Url = "http://192.168.100.84/Servicio%20Web/Service_Bdd.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event numeroPedidoCompletedEventHandler numeroPedidoCompleted;
        
        /// <remarks/>
        public event ValidarUsuarioCompletedEventHandler ValidarUsuarioCompleted;
        
        /// <remarks/>
        public event ConsultaProductoCompletedEventHandler ConsultaProductoCompleted;
        
        /// <remarks/>
        public event BusquedaDocumentoCompletedEventHandler BusquedaDocumentoCompleted;
        
        /// <remarks/>
        public event RegistroPedidoCompletedEventHandler RegistroPedidoCompleted;
        
        /// <remarks/>
        public event ConsultaCategoriaCompletedEventHandler ConsultaCategoriaCompleted;
        
        /// <remarks/>
        public event TotalPedidoCompletedEventHandler TotalPedidoCompleted;
        
        /// <remarks/>
        public event EstadoPedidoCompletedEventHandler EstadoPedidoCompleted;
        
        /// <remarks/>
        public event BusquedaClienteMovilCompletedEventHandler BusquedaClienteMovilCompleted;
        
        /// <remarks/>
        public event TiempoEsperaCompletedEventHandler TiempoEsperaCompleted;
        
        /// <remarks/>
        public event EliminarProductoCompletedEventHandler EliminarProductoCompleted;
        
        /// <remarks/>
        public event guardarActualizarClienteCompletedEventHandler guardarActualizarClienteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("192.168.100.84/numeroPedido", RequestNamespace="192.168.100.84", ResponseNamespace="192.168.100.84", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string numeroPedido() {
            object[] results = this.Invoke("numeroPedido", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void numeroPedidoAsync() {
            this.numeroPedidoAsync(null);
        }
        
        /// <remarks/>
        public void numeroPedidoAsync(object userState) {
            if ((this.numeroPedidoOperationCompleted == null)) {
                this.numeroPedidoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnumeroPedidoOperationCompleted);
            }
            this.InvokeAsync("numeroPedido", new object[0], this.numeroPedidoOperationCompleted, userState);
        }
        
        private void OnnumeroPedidoOperationCompleted(object arg) {
            if ((this.numeroPedidoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.numeroPedidoCompleted(this, new numeroPedidoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("192.168.100.84/ValidarUsuario", RequestNamespace="192.168.100.84", ResponseNamespace="192.168.100.84", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ValidarUsuario(string usuario, string contrasena, int rolcodigo) {
            object[] results = this.Invoke("ValidarUsuario", new object[] {
                        usuario,
                        contrasena,
                        rolcodigo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ValidarUsuarioAsync(string usuario, string contrasena, int rolcodigo) {
            this.ValidarUsuarioAsync(usuario, contrasena, rolcodigo, null);
        }
        
        /// <remarks/>
        public void ValidarUsuarioAsync(string usuario, string contrasena, int rolcodigo, object userState) {
            if ((this.ValidarUsuarioOperationCompleted == null)) {
                this.ValidarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidarUsuarioOperationCompleted);
            }
            this.InvokeAsync("ValidarUsuario", new object[] {
                        usuario,
                        contrasena,
                        rolcodigo}, this.ValidarUsuarioOperationCompleted, userState);
        }
        
        private void OnValidarUsuarioOperationCompleted(object arg) {
            if ((this.ValidarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidarUsuarioCompleted(this, new ValidarUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("192.168.100.84/ConsultaProducto", RequestNamespace="192.168.100.84", ResponseNamespace="192.168.100.84", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] ConsultaProducto(string idcategoria) {
            object[] results = this.Invoke("ConsultaProducto", new object[] {
                        idcategoria});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaProductoAsync(string idcategoria) {
            this.ConsultaProductoAsync(idcategoria, null);
        }
        
        /// <remarks/>
        public void ConsultaProductoAsync(string idcategoria, object userState) {
            if ((this.ConsultaProductoOperationCompleted == null)) {
                this.ConsultaProductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaProductoOperationCompleted);
            }
            this.InvokeAsync("ConsultaProducto", new object[] {
                        idcategoria}, this.ConsultaProductoOperationCompleted, userState);
        }
        
        private void OnConsultaProductoOperationCompleted(object arg) {
            if ((this.ConsultaProductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaProductoCompleted(this, new ConsultaProductoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("192.168.100.84/BusquedaDocumento", RequestNamespace="192.168.100.84", ResponseNamespace="192.168.100.84", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet BusquedaDocumento(int codigoPedido) {
            object[] results = this.Invoke("BusquedaDocumento", new object[] {
                        codigoPedido});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void BusquedaDocumentoAsync(int codigoPedido) {
            this.BusquedaDocumentoAsync(codigoPedido, null);
        }
        
        /// <remarks/>
        public void BusquedaDocumentoAsync(int codigoPedido, object userState) {
            if ((this.BusquedaDocumentoOperationCompleted == null)) {
                this.BusquedaDocumentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBusquedaDocumentoOperationCompleted);
            }
            this.InvokeAsync("BusquedaDocumento", new object[] {
                        codigoPedido}, this.BusquedaDocumentoOperationCompleted, userState);
        }
        
        private void OnBusquedaDocumentoOperationCompleted(object arg) {
            if ((this.BusquedaDocumentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BusquedaDocumentoCompleted(this, new BusquedaDocumentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("192.168.100.84/RegistroPedido", RequestNamespace="192.168.100.84", ResponseNamespace="192.168.100.84", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RegistroPedido(int codigoPedido, string producto, int unidades, int cliente) {
            object[] results = this.Invoke("RegistroPedido", new object[] {
                        codigoPedido,
                        producto,
                        unidades,
                        cliente});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RegistroPedidoAsync(int codigoPedido, string producto, int unidades, int cliente) {
            this.RegistroPedidoAsync(codigoPedido, producto, unidades, cliente, null);
        }
        
        /// <remarks/>
        public void RegistroPedidoAsync(int codigoPedido, string producto, int unidades, int cliente, object userState) {
            if ((this.RegistroPedidoOperationCompleted == null)) {
                this.RegistroPedidoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegistroPedidoOperationCompleted);
            }
            this.InvokeAsync("RegistroPedido", new object[] {
                        codigoPedido,
                        producto,
                        unidades,
                        cliente}, this.RegistroPedidoOperationCompleted, userState);
        }
        
        private void OnRegistroPedidoOperationCompleted(object arg) {
            if ((this.RegistroPedidoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegistroPedidoCompleted(this, new RegistroPedidoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("192.168.100.84/ConsultaCategoria", RequestNamespace="192.168.100.84", ResponseNamespace="192.168.100.84", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] ConsultaCategoria() {
            object[] results = this.Invoke("ConsultaCategoria", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultaCategoriaAsync() {
            this.ConsultaCategoriaAsync(null);
        }
        
        /// <remarks/>
        public void ConsultaCategoriaAsync(object userState) {
            if ((this.ConsultaCategoriaOperationCompleted == null)) {
                this.ConsultaCategoriaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultaCategoriaOperationCompleted);
            }
            this.InvokeAsync("ConsultaCategoria", new object[0], this.ConsultaCategoriaOperationCompleted, userState);
        }
        
        private void OnConsultaCategoriaOperationCompleted(object arg) {
            if ((this.ConsultaCategoriaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultaCategoriaCompleted(this, new ConsultaCategoriaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("192.168.100.84/TotalPedido", RequestNamespace="192.168.100.84", ResponseNamespace="192.168.100.84", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TotalPedido(int codigoPedido) {
            object[] results = this.Invoke("TotalPedido", new object[] {
                        codigoPedido});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TotalPedidoAsync(int codigoPedido) {
            this.TotalPedidoAsync(codigoPedido, null);
        }
        
        /// <remarks/>
        public void TotalPedidoAsync(int codigoPedido, object userState) {
            if ((this.TotalPedidoOperationCompleted == null)) {
                this.TotalPedidoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTotalPedidoOperationCompleted);
            }
            this.InvokeAsync("TotalPedido", new object[] {
                        codigoPedido}, this.TotalPedidoOperationCompleted, userState);
        }
        
        private void OnTotalPedidoOperationCompleted(object arg) {
            if ((this.TotalPedidoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TotalPedidoCompleted(this, new TotalPedidoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("192.168.100.84/EstadoPedido", RequestNamespace="192.168.100.84", ResponseNamespace="192.168.100.84", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int EstadoPedido(int codigoPedido, string opcion) {
            object[] results = this.Invoke("EstadoPedido", new object[] {
                        codigoPedido,
                        opcion});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void EstadoPedidoAsync(int codigoPedido, string opcion) {
            this.EstadoPedidoAsync(codigoPedido, opcion, null);
        }
        
        /// <remarks/>
        public void EstadoPedidoAsync(int codigoPedido, string opcion, object userState) {
            if ((this.EstadoPedidoOperationCompleted == null)) {
                this.EstadoPedidoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEstadoPedidoOperationCompleted);
            }
            this.InvokeAsync("EstadoPedido", new object[] {
                        codigoPedido,
                        opcion}, this.EstadoPedidoOperationCompleted, userState);
        }
        
        private void OnEstadoPedidoOperationCompleted(object arg) {
            if ((this.EstadoPedidoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EstadoPedidoCompleted(this, new EstadoPedidoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("192.168.100.84/BusquedaClienteMovil", RequestNamespace="192.168.100.84", ResponseNamespace="192.168.100.84", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string BusquedaClienteMovil(string cedula) {
            object[] results = this.Invoke("BusquedaClienteMovil", new object[] {
                        cedula});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BusquedaClienteMovilAsync(string cedula) {
            this.BusquedaClienteMovilAsync(cedula, null);
        }
        
        /// <remarks/>
        public void BusquedaClienteMovilAsync(string cedula, object userState) {
            if ((this.BusquedaClienteMovilOperationCompleted == null)) {
                this.BusquedaClienteMovilOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBusquedaClienteMovilOperationCompleted);
            }
            this.InvokeAsync("BusquedaClienteMovil", new object[] {
                        cedula}, this.BusquedaClienteMovilOperationCompleted, userState);
        }
        
        private void OnBusquedaClienteMovilOperationCompleted(object arg) {
            if ((this.BusquedaClienteMovilCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BusquedaClienteMovilCompleted(this, new BusquedaClienteMovilCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("192.168.100.84/TiempoEspera", RequestNamespace="192.168.100.84", ResponseNamespace="192.168.100.84", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TiempoEspera(int pedido) {
            object[] results = this.Invoke("TiempoEspera", new object[] {
                        pedido});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TiempoEsperaAsync(int pedido) {
            this.TiempoEsperaAsync(pedido, null);
        }
        
        /// <remarks/>
        public void TiempoEsperaAsync(int pedido, object userState) {
            if ((this.TiempoEsperaOperationCompleted == null)) {
                this.TiempoEsperaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTiempoEsperaOperationCompleted);
            }
            this.InvokeAsync("TiempoEspera", new object[] {
                        pedido}, this.TiempoEsperaOperationCompleted, userState);
        }
        
        private void OnTiempoEsperaOperationCompleted(object arg) {
            if ((this.TiempoEsperaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TiempoEsperaCompleted(this, new TiempoEsperaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("192.168.100.84/EliminarProducto", RequestNamespace="192.168.100.84", ResponseNamespace="192.168.100.84", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int EliminarProducto(int codigoPedido, string producto, int unidades) {
            object[] results = this.Invoke("EliminarProducto", new object[] {
                        codigoPedido,
                        producto,
                        unidades});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void EliminarProductoAsync(int codigoPedido, string producto, int unidades) {
            this.EliminarProductoAsync(codigoPedido, producto, unidades, null);
        }
        
        /// <remarks/>
        public void EliminarProductoAsync(int codigoPedido, string producto, int unidades, object userState) {
            if ((this.EliminarProductoOperationCompleted == null)) {
                this.EliminarProductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarProductoOperationCompleted);
            }
            this.InvokeAsync("EliminarProducto", new object[] {
                        codigoPedido,
                        producto,
                        unidades}, this.EliminarProductoOperationCompleted, userState);
        }
        
        private void OnEliminarProductoOperationCompleted(object arg) {
            if ((this.EliminarProductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarProductoCompleted(this, new EliminarProductoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("192.168.100.84/guardarActualizarCliente", RequestNamespace="192.168.100.84", ResponseNamespace="192.168.100.84", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int guardarActualizarCliente(string tipoBusqueda, int codigoCliente, string nombreCliente, string apellidoCliente, string cedulaCliente, string correoCliente, string direccionCliente, int codigoEstado) {
            object[] results = this.Invoke("guardarActualizarCliente", new object[] {
                        tipoBusqueda,
                        codigoCliente,
                        nombreCliente,
                        apellidoCliente,
                        cedulaCliente,
                        correoCliente,
                        direccionCliente,
                        codigoEstado});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void guardarActualizarClienteAsync(string tipoBusqueda, int codigoCliente, string nombreCliente, string apellidoCliente, string cedulaCliente, string correoCliente, string direccionCliente, int codigoEstado) {
            this.guardarActualizarClienteAsync(tipoBusqueda, codigoCliente, nombreCliente, apellidoCliente, cedulaCliente, correoCliente, direccionCliente, codigoEstado, null);
        }
        
        /// <remarks/>
        public void guardarActualizarClienteAsync(string tipoBusqueda, int codigoCliente, string nombreCliente, string apellidoCliente, string cedulaCliente, string correoCliente, string direccionCliente, int codigoEstado, object userState) {
            if ((this.guardarActualizarClienteOperationCompleted == null)) {
                this.guardarActualizarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnguardarActualizarClienteOperationCompleted);
            }
            this.InvokeAsync("guardarActualizarCliente", new object[] {
                        tipoBusqueda,
                        codigoCliente,
                        nombreCliente,
                        apellidoCliente,
                        cedulaCliente,
                        correoCliente,
                        direccionCliente,
                        codigoEstado}, this.guardarActualizarClienteOperationCompleted, userState);
        }
        
        private void OnguardarActualizarClienteOperationCompleted(object arg) {
            if ((this.guardarActualizarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.guardarActualizarClienteCompleted(this, new guardarActualizarClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void numeroPedidoCompletedEventHandler(object sender, numeroPedidoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class numeroPedidoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal numeroPedidoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void ValidarUsuarioCompletedEventHandler(object sender, ValidarUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void ConsultaProductoCompletedEventHandler(object sender, ConsultaProductoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaProductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaProductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void BusquedaDocumentoCompletedEventHandler(object sender, BusquedaDocumentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BusquedaDocumentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BusquedaDocumentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void RegistroPedidoCompletedEventHandler(object sender, RegistroPedidoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegistroPedidoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegistroPedidoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void ConsultaCategoriaCompletedEventHandler(object sender, ConsultaCategoriaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultaCategoriaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultaCategoriaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void TotalPedidoCompletedEventHandler(object sender, TotalPedidoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TotalPedidoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TotalPedidoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void EstadoPedidoCompletedEventHandler(object sender, EstadoPedidoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EstadoPedidoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EstadoPedidoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void BusquedaClienteMovilCompletedEventHandler(object sender, BusquedaClienteMovilCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BusquedaClienteMovilCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BusquedaClienteMovilCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void TiempoEsperaCompletedEventHandler(object sender, TiempoEsperaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TiempoEsperaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TiempoEsperaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void EliminarProductoCompletedEventHandler(object sender, EliminarProductoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminarProductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EliminarProductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void guardarActualizarClienteCompletedEventHandler(object sender, guardarActualizarClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class guardarActualizarClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal guardarActualizarClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591